services:
  postgres:
    image: postgres:latest
    container_name: todo-it-postgres
    env_file:
      # env 파일을 이름 변경시 정상적으로 로드되지 못하므로, .env로 고정되어야함
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:

